import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as html from "parse5";
import postcss from "postcss";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const read = name => fs.readFileSync(path.join(root, name), "utf8");
const write = (name, content) => {
  fs.mkdirSync(path.dirname(path.join(root, name)), { recursive: true });
  fs.writeFileSync(path.join(root, name), content);
};
const products = JSON.parse(read("data/line-page-products.json")).products;
const release = JSON.parse(read("data/line-page-release.json"));
const base = "https://stefanellit.github.io/reelcalc-wizard/";
const escape = text => String(text).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
const attr = (node, name) => node.attrs?.find(a => a.name === name)?.value;
function setAttr(node, name, value) {
  const old = node.attrs.find(a => a.name === name);
  if (old) old.value = value;
  else node.attrs.push({ name, value });
}
function nodes(node, predicate) {
  return [...(predicate(node) ? [node] : []), ...(node.childNodes || []).flatMap(child => nodes(child, predicate))];
}

// Scope every selector, including resets, so a guide cannot restyle the host site.
const css = postcss.parse(read("css/line-page.css") + "\n" + read("css/line-page-gold.css"));
css.walkRules(rule => {
  const selectors = rule.selectors.filter(selector => selector !== "html").map(selector => {
    if (selector === ":root" || selector === "body") return ".rc-line-page";
    if (selector.startsWith(".rc-line-page")) return selector;
    if (selector.startsWith(".rc-line-gold")) return selector.replace(".rc-line-gold", ".rc-line-page.rc-line-gold");
    return ".rc-line-page " + selector;
  });
  if (!selectors.length) rule.remove();
  else rule.selectors = selectors;
});
css.walkDecls(decl => {
  // Host themes often change the root font size; retain the approved dimensions.
  decl.value = decl.value.replace(/\b(\d*\.?\d+)rem\b/g, (_, value) => `${Number(value) * 16}px`);
});
css.walkAtRules("media", rule => {
  if (/^\(max-width: \d+px\)$/.test(rule.params)) {
    rule.after(rule.clone({ name: "container", params: "rc-line-guide " + rule.params }));
  }
});
css.append(postcss.parse(`
.rc-line-page { box-sizing: border-box; font-size: 16px; container: rc-line-guide / inline-size; }
.rc-line-page .rc-product-title { margin: 0; font-size: 38px; line-height: 1.14; color: var(--rc-ink); }
@media (max-width: 720px) { .rc-line-page .rc-product-title { font-size: 30px; } }
@container rc-line-guide (max-width: 720px) { .rc-line-page .rc-product-title { font-size: 30px; } }
`));
write("css/line-page-embed.css", "/* Generated by scripts/line-page-publishing/build.mjs. */\n" + css.toString());

const settings = [];
for (const id of release.products) {
  const product = products[id];
  if (!product) throw new Error(`Missing launch product ${id}`);
  const document = html.parse(read(`examples/line-pages/${id}.html`));
  const page = nodes(document, n => attr(n, "data-reelcalc-line-page") !== undefined)[0];
  const schema = nodes(document, n => n.tagName === "script" && attr(n, "type") === "application/ld+json")[0];
  if (!page || !schema) throw new Error(`Missing guide or structured data for ${id}`);
  page.tagName = "article";
  setAttr(page, "data-asset-base", base);
  const title = nodes(page, n => n.tagName === "h1")[0];
  title.tagName = "h2";
  setAttr(title, "class", "rc-product-title");
  for (const image of nodes(page, n => n.tagName === "img")) {
    const imagePath = new URL(attr(image, "src"), base + "examples/line-pages/").pathname.replace("/reelcalc-wizard/", "");
    setAttr(image, "data-line-page-image", imagePath);
    setAttr(image, "src", new URL(imagePath, base).href);
  }
  schema.parentNode = page;
  page.childNodes.push(schema);
  write(`components/line-pages/${id}.html`, html.serializeOuter(page) + "\n");

  const snippet = `<div id="reelcalc-line-page-app"><p>Loading the ${escape(product.h1)} guide...</p><noscript><p>This guide needs JavaScript. <a href="${base}examples/line-pages/${id}.html">Read the diameter chart and line guide</a>.</p></noscript></div>\n<script src="${base}js/line-page-loader.js" data-product="${id}"></script>\n`;
  write(`generated/line-pages/${id}-squarespace-snippet.html`, snippet);
  const localSnippet = snippet.replace(`src="${base}js/line-page-loader.js"`, 'src="../../js/line-page-loader.js"');
  write(`previews/line-pages/${id}-hosted.html`, `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex"><title>${escape(product.h1)} - Hosted preview</title><style>html{font-size:20px}body{margin:0;background:#f3f3f3;font-family:Georgia,serif;color:#342838}body>header,body>footer{padding:18px 24px}body>main{max-width:1120px;margin:auto;background:white}h1{font-size:32px;padding:24px;margin:0}button{font-family:Georgia,serif}a{color:#86144d}img{max-width:100%}</style></head><body><header id="host-header"><a href="https://www.reelcalc.com/">ReelCalc</a></header><main><h1>${escape(product.h1)}</h1>${localSnippet}</main><footer id="host-footer">ReelCalc</footer></body></html>\n`);
  settings.push({ id, title: product.h1, slug: product.slug, url: "https://www.reelcalc.com/lines/p/" + product.slug, seoTitle: product.seoTitle, seoDescription: product.metaDescription, excerpt: product.quickSummary, thumbnail: product.localImagePath, snippet: `generated/line-pages/${id}-squarespace-snippet.html` });
}
write("generated/line-pages/launch-settings.json", JSON.stringify(settings, null, 2) + "\n");
console.log(`Built ${settings.length} hosted components, short snippets, host-theme previews, and launch settings.`);
